name: google_map_app
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter 
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.6.1
  location: ^6.0.2
  flutter_polyline_points: ^2.0.0
  flutter_plugin_android_lifecycle: ^2.0.19
  http: ^1.2.1
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  lottie: ^3.1.2
  mqtt_client: ^10.2.1
  flutter_launcher_icons: ^0.13.1
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: 
  uses-material-design: true

  assets:
    - assets/icons/car.png
    - assets/icons/carGreen.png
    - assets/icons/logo.png
    - assets/icons/infoWhite.png


flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/icons/icon.png"
  remove_alpha_ios: true

  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
